
add_library(vlneval SHARED ${SOURCES})

target_link_directories(vlneval PRIVATE ${TENSORFLOW_LIBRARY_DIRS})
target_link_libraries  (vlneval PRIVATE ${TENSORFLOW_LINK_LIBRARIES})

target_include_directories(
    vlneval
        PRIVATE ${EIGEN3_INCLUDE_DIRS}
        PRIVATE ${TENSORFLOW_INCLUDE_DIRS}
        PRIVATE ${PROTOBUF_INCLUDE_DIRS}
        PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include
        PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/src
)

install(
    TARGETS vlneval
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
    INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)

install(DIRECTORY "include/" DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})

# Generating pkg-config
set(PKG_CONFIG_LIBS "-lvlneval")

configure_file(
    "${CMAKE_CURRENT_SOURCE_DIR}/pkg-config.pc.in"
    "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}.pc"
    @ONLY
)

install(
    FILES "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}.pc"
    DESTINATION ${CMAKE_INSTALL_LIBDIR}/pkgconfig/
)

